version: '2'

services:
  linking-server:
    image: weather-reminder-server-docker-image
    volumes:
      - ./deploy:/deploy/weather-reminder # host의 ./deploy 디렉토리를 컨테이너의 /deploy/weather-reminder에 마운트 하겠다.
    ports:
      - "1024:1026" # a : b -> b 포트에서 받는 트래픽을 a로 넘겨준다